# Generated by Django 4.2.7 on 2026-04-03 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('codigo_reserva', models.CharField(max_length=20, unique=True, verbose_name='Código de reserva')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de entrada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('num_huespedes', models.PositiveIntegerField(default=1, verbose_name='Número de huéspedes')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('check_in', 'Check-in realizado'), ('check_out', 'Check-out realizado'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('habitacion', models.ForeignKey(db_column='habitacion_id', on_delete=django.db.models.deletion.PROTECT, to='rooms.habitacion', verbose_name='Habitación')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('detalles', models.JSONField(blank=True, default=dict, verbose_name='Detalles')),
                ('reserva', models.ForeignKey(db_column='reserva_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.reserva', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de reserva',
                'verbose_name_plural': 'Historial de reservas',
                'db_table': 'historial_reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
