# Generated by Django 4.2.7 on 2026-04-03 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('capacidad_maxima', models.PositiveIntegerField(default=2, verbose_name='Capacidad máxima')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='Amenities')),
            ],
            options={
                'verbose_name': 'Tipo de habitación',
                'verbose_name_plural': 'Tipos de habitación',
                'db_table': 'tipos_habitacion',
                'ordering': ['precio_base'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('piso', models.PositiveIntegerField(default=1, verbose_name='Piso')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En mantenimiento'), ('limpieza', 'En limpieza')], default='disponible', max_length=20, verbose_name='Estado')),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio actual')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('caracteristicas', models.JSONField(blank=True, default=dict, verbose_name='Características')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('tipo', models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.PROTECT, to='rooms.tipohabitacion', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitaciones',
                'ordering': ['piso', 'numero'],
            },
        ),
    ]
